### ISSUE TITLE
Exception when using checkout 

### ISSUE THREAD

**Issue by GamingGuy003** [AcaciaLinux/branch#78]
45 {"command":"CHECKOUT","payload":"crosstools"}

throws:

Traceback (most recent call last):
  File "/opt/branch/master/src/manager/client.py", line 108, in receive_command
    res: BranchResponse = commands.handle_command(self, request)
  File "/opt/branch/master/src/commands/commands.py", line 16, in handle_command
    return handle_command_controller(branch_client, branch_request)
  File "/opt/branch/master/src/commands/commands.py", line 83, in handle_command_controller
    return BranchResponse(BranchStatus.OK, pkg_build.get_dict())
AttributeError: 'package_build' object has no attribute 'get_dict'

**Comment by zimsneexh** [comment]
Caused by out-of-date branchcommons. Make sure to update your submodules and run `make install_submodules`
